#include "argo.h"
#include <stdio.h>

int init_out_file(){
    FILE *f = fopen(out_file, "w");
    if(!f) return ERR;
    const char *template = "//Code generated by Argo Navis\n\n#include <stdio.h>\n#include <stdlib.h>\n"
                            "#include <string.h>\n#include \"argo.h\"\n\nint main(void){\n";
    fprintf(f,"%s", template); 
    fclose(f);
    return SUC;
}
int write_out(const char *s){
    FILE *f = fopen(out_file, "a");
    if(!f) return ERR;
    fprintf(f,"\t%s\n", s); 
    fclose(f);
    return SUC;
}
int write_outws(const wchar_t *ws){
    FILE *f = fopen(out_file, "a");
    if(!f) return ERR;
    fprintf(f,"\t%ls\n", ws); 
    fclose(f);
    return SUC;
}

int close_file(){
    FILE *f = fopen(out_file, "a");
    if(!f) return ERR;
    const char *template = "\n\n\treturn 0;\n}\n";
    fprintf(f,"%s", template); 
    fclose(f);
    return SUC;

}
