//Code generated by Argo Navis

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "argo.h"

int main(void){
	string a;
	string_new(&a);
	string_concat(&a,"Hello world");
	int b=123;
	char c='c';
	puts("Hello");
	printf("%ls\n",a);
	printf("%d\n",b);
	printf("%c\n",c);
	string d;
	string_new(&d);
	string_concat(&d,"Goodbye world");
	printf("%ls\n",d);
	printf("%d\n",12345);
	printf("%c\n",'e');
	string_free(&a);
	string_free(&d);


	return 0;
}
